### ISSUE TITLE
Ubuntu installed orangepi

### ISSUE THREAD

**Issue by batsuurib** [zhgzhg/LoRaPacketForwarder#16]
Hello

Can ubuntu installed orangepi zer 2w install packetforwarder and use it

Thank you for always quick responses

**Comment by zhgzhg** [comment]
Hi @batsuurib ,
It should be able to work with it, however I have not tested on that particular board.

Additionally may want to use the WiringPi library from the Ubuntu distribution instead of installing the version bundled in this repository. The rest of the installation steps should remain the same.

**Comment by batsuurib** [comment]
Thank you so much

It was good news
